name: jsmn
version: 1.0-SNAPSHOT
main: com.jsmn.plugin.Main
api-version: 1.20
description: Run pupil-authored JavaScript files inside Minecraft.
author: jsmn

commands:
  runscript:
    description: Run a JavaScript file from the scripts folder. The script can use the 'player' object (sendMessage, getName, getX/Y/Z, getHealth) and the 'drone' object to place blocks (box, sphere, maze, castle, rainbow) and move around the world.
    usage: /<command> <filename>
    aliases: [rs]
    permission: jsmn.runscript
    permission-message: You do not have permission to run scripts.
  listscripts:
    description: List all available JavaScript files in the scripts folder.
    usage: /<command>
    aliases: [ls]
    permission: jsmn.runscript
    permission-message: You do not have permission to list scripts.
  box:
    description: Place a solid box of blocks at your position. Dimensions default to 1×1×1 if not given.
    usage: /<command> <material> [width] [height] [depth]
    permission: jsmn.runscript
    permission-message: You do not have permission to use this command.
  box0:
    description: Place a hollow box (walls only, no floor or ceiling) at your position.
    usage: /<command> <material> [width] [height] [depth]
    permission: jsmn.runscript
    permission-message: You do not have permission to use this command.
  maze:
    description: Generate a random maze at your position. cols and rows set the number of corridor cells; height sets the wall height in blocks (default 3).
    usage: /<command> <material> <cols> <rows> [height]
    permission: jsmn.runscript
    permission-message: You do not have permission to use this command.
  sphere:
    description: Build a solid sphere at your position. Radius defaults to 10, maximum 64.
    usage: /<command> <material> [radius]
    permission: jsmn.runscript
    permission-message: You do not have permission to use this command.
  sphere0:
    description: Build a hollow sphere (1 block thick shell) at your position. Radius defaults to 10, maximum 64.
    usage: /<command> <material> [radius]
    permission: jsmn.runscript
    permission-message: You do not have permission to use this command.
  rainbow:
    description: Build a rainbow arch in front of you. Radius defaults to 18, minimum 7.
    usage: /<command> [radius]
    permission: jsmn.runscript
    permission-message: You do not have permission to use this command.
  castle:
    description: Build a medieval castle with towers, battlements and a gate at your position. Side defaults to 12, height defaults to 10.
    usage: /<command> <material> [side] [height]
    permission: jsmn.runscript
    permission-message: You do not have permission to use this command.
  savescript:
    description: Save a JavaScript file to your personal scripts folder. Everything after the name is saved as the script content.
    usage: /<command> <name> <content...>
    permission: jsmn.runscript
    permission-message: You do not have permission to save scripts.

permissions:
  jsmn.runscript:
    description: Allows running and listing JavaScript files.
    default: true
